site_name: XCRI Toolkit Docs
site_url: https://xsede.org/xcri
site_description: XCRI Toolkit documentation

repo_url: https://github.com/XSEDE/XCRI-Docs

docs_dir: docs

pages:
- Home: 'index.md'
- Toolkits:
  - XCBC: 
    - RHEL 8 Installation Tutorial: 'toolkits/xcbc-2.0-installation.md'
    - RHEL 7 Installation Tutorial: 'toolkits/xcbc-installation.md'
    - GPU Node Build: 'toolkits/gpu-nodes.md'
    - Custom Node Images: 'toolkits/xcbc-new-image.md'
    - Slurmdbd Configuration: 'toolkits/slurmdbd-config.md'
    - AD Integration: 'toolkits/ActiveDirectoryIntegration.md'
  - Cluster Monitoring Toolkit: 
    - Installation: 'toolkits/clustermon-installation.md'
    - Configuration: 'toolkits/clustermon-config.md'
  - Jetstream VC: 
    - Installation: 'toolkits/vc-installation.md'
  - Container Template Library: 
    - Quick Start Guide: 'toolkits/ctl/ctlquick.md'
  - OpenStack Installation:
    - Openstack Installation Guide: 'toolkits/OpenstackInstallation.md'
- Contact Us: 'contact-us.md'
- Contributing: 'contributions.md'

theme: readthedocs

#extra_css:
#  - css/extra.css

markdown_extensions:
  - toc:
     permalink: True
  - admonition
